### ISSUE TITLE
nil-pointer in getTestSigChan

### ISSUE THREAD

**Issue by IvoGoman** [oklog/run#26]
After upgrading to the latest digest I am seeing: 
```bash
panic: interface conversion: interface {} is nil, not <-chan os.Signal

goroutine 108 [running]:
github.com/oklog/run.getTestSigChan(...)
	/go/pkg/mod/github.com/oklog/run@v1.1.1-0.20231129054641-daf88ede3394/actors.go:51
github.com/oklog/run.SignalHandler.func1()
	/go/pkg/mod/github.com/oklog/run@v1.1.1-0.20231129054641-daf88ede3394/actors.go:31 +0x355
github.com/oklog/run.(*Group).Run.func1({0xc0006a1710?, 0xc000690a50?})
	/go/pkg/mod/github.com/oklog/run@v1.1.1-0.20231129054641-daf88ede3394/group.go:38 +0x29
created by github.com/oklog/run.(*Group).Run in goroutine 1
	/go/pkg/mod/github.com/oklog/run@v1.1.1-0.20231129054641-daf88ede3394/group.go:37 +0x67 
```

`getTestSigChan` is only used within tests, but causes an nil-pointer if used outside.

I was able to reproduce the nil-pointer: https://go.dev/play/p/JFXak3UIrB6
From what I can tell there needs to be a nil check on the value retrieved from the context before the type assertion.

**Comment by peterbourgon** [comment]
How are you calling `getTestSigChan` in the first place?
